### ISSUE TITLE
Undeploy

### ISSUE THREAD

**Issue by Dreadwall** [picoCTF/picoCTF-shell-manager#60]
shell_manager undeploy has a few bugs, I'm gonna start working on it just wanted to document them. 
1. Calling undeploy with an incorrect number of instances leaves orphaned instances that cannot be removed. 
    A. Deploy -n 3 NAME
    B. undeploy NAME
    C. undeploy -n 2 NAME
Both B and C leave orphaned instances that cannot be removed using deploy.

2. If undeploy is given the correct number of instances, it is correctly removed from the problems directory, but shell_manager status shows the problem with 0 instances.  
    A. Deploy -n 3 NAME
    B. undeploy -n 3 NAME

3. Following from 2, if there are 0 instances of a problem, and load deployment is selected from the management tab, the problems aren't removed from the deployment. It does not install the question again, the number of problems installed decreases, but the problem remains available on the platform.

**Comment by tim-becker** [comment]
Hey, thanks for submitting this. For the first two issues, I think there is some misunderstanding.

The `-n` flag is perhaps misnamed, because it actually means "the range of instances IDs from 0 to n-1". The behavior you are seeing in the first issue is actually expected.
Also, the instances aren't orphaned. They can still be undeployed using the `-i [ID]` option.

For the second issue, note that `status` will list all installed problems and their corresponding instances. A problem is considered installed if the debian package for it has been installed (and the source code is placed under /opt/hacksports/sources). Even if a problem has zero deployed instances, it is still considered installed.

The last issue is an issue that we may need to fix. In more detail, this is happening because the web server loads the instances using the `shell_manager publish` command, which only includes problems that have instances. I see two possible solutions to this:

1. On the web server, we can detect that a problem is no longer being supplied by the shell server, and remove all instances of it that are from that server.
2. We can make `publish` include problems that have zero instances.

In either case, we should not remove the problem itself from the database, but instead empty its instance list. The web server code currently depends too heavily on the problems always existing. We'll have to treat problems with an empty instance list the same as disabled problems.

Until we fix this, a workaround is to disable the problem on the admin page, and it will be treated as though it was removed.

Thanks again for reporting these!

**Comment by tim-becker** [comment]
After thinking a bit more, perhaps a clean fix would be to automatically disable problems that have zero instances, and reject any attempts to enable them until instances are added.

**Comment by cganas** [comment]
I would prefer option 2 of Tim's suggested workarounds (publishing zero instance problems). I think it makes a lot of sense to disable problems that have zero instances. Though I'm not sure what "disabling" should mean.

Problems are either enabled or disabled and stay visible to the admin management page. I would argue a problem with **0** instances should be hidden from view and implicitly disabled, i.e. 

hidden? `len(problem["instances"]) == 0`
disabled? `problem["disabled"] or hidden?`

This should also affect bundle visibility. A bundle is included iff there exists some published problem in that bundle. This can easily be modified to **a bundle is included iff there exists some published problem with non-zero instances in that bundle.** I believe that change should be sufficient.
